- name: include vars
  include_vars:
    file: default.yml

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Upgrade existing linux packages
  apt: upgrade=dist
  sudo: yes

- name: Install the kitchen sink
  action: apt pkg={{item}} state=installed update_cache=true
  sudo: yes
  with_items:
    - autoconf
    - automake
    - bison
    - build-essential
    - curl
    - gawk
    - git-core
    - git
    - libxml2-dev
    - libffi-dev
    - libyaml-dev
    - libssl-dev
    - libsqlite3-dev
    - libgdbm-dev
    - libncurses5-dev
    - libreadline6-dev
    - libtool
    - libyaml-dev
    - nfs-common # make virtualbox faster
    - pkg-config
    - sqlite3
    - vim
    - zlib1g-dev
    - htop
    - iftop
    - nodejs
    - python-pycurl # for postgresql playbook, uses apt_pkg
    - python-software-properties # for `add-apt-repository` command
    - fail2ban
    - ufw
    - unattended-upgrades

#
# - name: Create rails user
#   include_role:
#     static: yes
#     name: roles/external/create-rails-user
#   become: yes
#   become_method: sudo
#
# - name: Install rbenv
#   include_role:
#     static: yes
#     name: roles/external/rbenv
#   become: yes
#   become_method: sudo
#   become_user: "{{ rails_user }}"

- name: Install ruby
  include_role:
    static: yes
    name: roles/external/ruby
  become: yes
  become_method: sudo
  become_user: "{{ rails_user }}"

# - name: Install postgres
#   include: external/postgresql/tasks/main.yml

# - name: Install nginx
#   include: external/nginx/tasks/main.yml
