# Most of this borrowed from https://github.com/leucos/ansible-rbenv-playbook

- name: Install rbenv
  git: repo=git://github.com/sstephenson/rbenv.git accept_hostkey=yes dest=~{{rails_user}}/.rbenv

- name: Create (if not exists) ~/.bash.d/
  file: dest=~{{rails_user}}/.bash.d/ state=directory

- name: Copy 50_rbenv.bash to ~/.bash.d/
  copy: src=50_rbenv.bash dest=~{{rails_user}}/.bash.d/50_rbenv.bash mode=700 owner={{rails_user}}

- name: Add rbenv to ~/.bash_profile
  # Clever: the task is idempotent because of the regexp=rbenv
  lineinfile: dest=~{{rails_user}}/.bash_profile regexp="rbenv" insertafter=EOF line="source ~/.bash.d/50_rbenv.bash" create=yes owner={{rails_user}}

- name: Create (if not exists) ~/.rbenv/plugns/
  file: path=~{{rails_user}}/.rbenv/plugins/ owner={{rails_user}} group={{rails_user}} mode=0755 state=directory

- name: Install ruby-build
  git: repo=git://github.com/sstephenson/ruby-build.git dest=~{{rails_user}}/.rbenv/plugins/ruby-build
